try {
    notExistingFunction();
}
catch {
    console.log('catched!');
}